server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: goodface-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/goodface?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  redis:
    host: ${SPRING_REDIS_HOST:127.0.0.1}
    port: ${SPRING_REDIS_PORT:6379}

dubbo:
  application:
    name: goodface-user
  protocol:
    name: dubbo
  registry:
    address: ${DUBBO_REGISTRY_ADDRESS:nacos://127.0.0.1:8848}
    check: false
  config-center:
    check: false

logging:
  level:
    root: INFO
    org.apache.dubbo: INFO