# Default values for goodface-user.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/goodface/goodface-user
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8002

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

env:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://rm-xxx.mysql.rds.aliyuncs.com:3306/goodface?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai"
  SPRING_DATASOURCE_USERNAME: "goodface"
  SPRING_DATASOURCE_PASSWORD: "strong-password"
  SPRING_REDIS_HOST: "r-xxx.redis.rds.aliyuncs.com"
  SPRING_REDIS_PORT: "6379"
  DUBBO_REGISTRY_ADDRESS: "nacos://nacos.internal:8848"